### ISSUE TITLE
Need a way to set value

### ISSUE THREAD

**Issue by agrover** [mrhooray/crc-rs#1]
I am trying to work with LVM metadata CRCs. Their crc calcs both use a nonstandard table, and also use an initial value of 0xf597a6cf instead of 0. I was able to work around this with a local copy of crc-rs and changing the value field in struct Digest to public, but wanted your thoughts on fixing it upstream.

for reference: https://git.fedorahosted.org/cgit/lvm2.git/tree/lib/misc/crc.c

**Comment by mrhooray** [comment]
custom table and initial value can be used via `update` function like 
```
update(0xf597a6cf, &lvm_crc_table, bytes);
```
but yeah we could make more sugar like taking initial value when creating a digest

**Comment by agrover** [comment]
ah, ok, will use update() as described. opened PR #3 for added sugar as you mentioned. Closing this issue, thanks!
