### ISSUE TITLE
`Digest<'a, W>` is no longer `Clone` in crc-3.2.0

### ISSUE THREAD

**Issue by daniestevez** [mrhooray/crc-rs#118]
Before crc-3.2.0, `Digest<'a, W>` was `Clone` if `W: Clone + Width`. In crc-3.2.0, `Digest<'a, W> = Digest<'a, W, Table<1>>`, which is not `Clone` because `Table<const L: usize>` is never `Clone`. This is an API-breaking change.

**Comment by akhilles** [comment]
Thanks for reporting, pushed 3.2.1 with the fix.

**Comment by daniestevez** [comment]
Thanks for fixing this!
