### ISSUE TITLE
Parallel computation of CRC

### ISSUE THREAD

**Issue by vandenoever** [mrhooray/crc-rs#12]
It would be nice to divide the load of calculation the CRC of multiple cores.

The function `Combine` in Ionic.Crc.CRC32 apparently can do this.

```C#
/// Combines the given CRC32 value with the current running total.
/// crc the crc value to be combined with this one
/// length the length of data the CRC value was calculated on</param>
public void Combine(int crc, int length);
```

https://github.com/r2d2rigo/dotnetzip-for-unity/blob/master/CommonSrc/CRC32.cs

**Comment by vandenoever** [comment]
Such a function is also present in zlib: `crc32_combine`.
http://zlib.net/manual.html

**Comment by mrhooray** [comment]
Closing for now. Please reopen if you'd like to add this functionality.
