### ISSUE TITLE
replace `Digest::new` with table specific digests

### ISSUE THREAD

**Issue by vitiral** [mrhooray/crc-rs#14]
Is there a reason there is`Digest::new` instead of just:
- `Digest::new_ieee()`
- `Digest::new_castagnoli()`

where those methods just copy the already computed tables.

With #13 this could remove `make_table` from the library. If the user wants to use their own table, couldn't they compute it (using a new crate `crc-table`) and pass it in?

I'm willing to work on this.

**Comment by vitiral** [comment]
I take back removing `make_table` from the library -- keep it in. But we should have table-specific digests that don't require using it (since they are precomputed)

**Comment by mrhooray** [comment]
> But we should have table-specific digests that don't require using it
Could you clarify this given context of #13 #16?

Creating custom digest is not high frequent use case and creating the table/struct once might be okay. Do you have a specific reason against doing so?

**Comment by vitiral** [comment]
I think this isn't really that importnat anymore.

Thanks
