### ISSUE TITLE
Faster generation of CRC tables

### ISSUE THREAD

**Issue by kitling** [mrhooray/crc-rs#27]
Wikipedia [suggests](https://en.wikipedia.org/wiki/Computation_of_cyclic_redundancy_checks#Generating_the_tables) that creating the tables can be done quicker by only computing for the powers of two, and then generating every other value by xoring the powers of two.

Whether or not this makes a big enough difference to matter is another question entirely, though.

**Comment by mrhooray** [comment]
don't see table generation being the limiting factor but feel free to take a stab if you'd like to

**Comment by kitling** [comment]
Yeah, I don't really think it's a limiting factor, either.
