### ISSUE TITLE
Consider writing the tables in hex

### ISSUE THREAD

**Issue by lnicola** [mrhooray/crc-rs#47]
This makes things easier for people searching for a CRC variant that matches some other existing code; compare https://docs.rs/crc/1.8.1/crc/crc32/constant.IEEE_TABLE.html with web.mit.edu/freebsd/head/sys/libkern/crc32.c.

**Comment by mrhooray** [comment]
closing as #55 has been merged - though it's going to a different direction with much more flexibility.
