### ISSUE TITLE
adding CalcType to crc::crcXX::update() is backwards incompatible

### ISSUE THREAD

**Issue by samhansen** [mrhooray/crc-rs#49]
Commit d1710151 in v1.9.0 adds a 4th CalcType arg to the crc::crcXX::update() routine.

This breaks all current users of update() in transitioning between 1.8.1 -> 1.9.0.

I'm filing this issue in case that wasn't an intentional backwards-incompatible breakage.

One example user is the ext4 package, which makes use of crc::crc32::update().  There is a pending pull-req to fix the ext4 crate, but as-is the build has been broken.

**Comment by mrhooray** [comment]
@samhansen thanks for raising this. It was not intended and sorry that it falls through the crack. 

Just yanked the version `cargo yank --vers 1.9.0`
