### ISSUE TITLE
Bump MSRV to 1.56

### ISSUE THREAD

**Issue by akhilles** [mrhooray/crc-rs#99]
To make use of:
- Compile-time assertions
- Const generics
- 2021 edition
- [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) field in Cargo manifest

**Comment by khrs** [comment]
Nice timing ;) I was pretty unhappy about your MSVR so as small weekend project I refreshed my old and crude [crcxx](https://crates.io/crates/crcxx) crate adding features i need most. Heh.
